---
metainfo:
  placement: AKH
  company: AKH
ansible_ip: 185.16.213.62
ansible_domainname: ix-hyper-02
ansible_host: "{{ ansible_ip }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
ansible_ssh_common_args: '-o IdentitiesOnly=yes -o PubkeyAuthentication=no'
