#!/usr/bin/env ansible-playbook
#
# Playbook to install and run Jenkins with nginx and TLS certificates on
# target nodes. Run it like usual executable script:
#
# > ./run-jenkins.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: jenkins
  remote_user: root
  roles:
    - { role: geerlingguy.jenkins, tags: ['jenkins'] }
