---
#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-redash.yml
#
- name: Install Redash 
  hosts: redash
  remote_user: root
  roles:
    - { role: xolog.redash, tags: ['redash'] }
