#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run docker on target nodes. Run it like usual
# executable script:
#
# > ./run-docker.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: docker_hosts
  become: yes
  remote_user: root

  roles:
    - { role: sorrowless.docker, tags: ['docker'] }

  tasks:
    - name: Ensure clearing docker images
      cron:
        name: "Clear docker images"
        user: "root"
        minute: "0"
        hour: "2"
        weekday: "6"
        job: "/usr/bin/docker image prune -af"
        state: present
      tags:
        - clean
