#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run taskd server
#
# > ./run-taskd.yml
#
---
- name: Configure target servers
  hosts: taskd_servers

  roles:
    - { role: sorrowless.taskd, tags: ['taskd'] }
