#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-atop.yml
#
---
- name: Setup atop
  hosts: atop

  roles:
    - { role: jtprogru.install_atop, tags: ['atop'] }
