#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install gitlab server
  hosts: gitlab_servers
  remote_user: root
  become: yes
  roles:
    - { role: ageres210784.ansible_gitlab, tags: ['gitlab'] }
