#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install glitchtip
  hosts: glitchtip_servers
  become: yes
  become_user: root
  vars:
    glitchtip_env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      SECRET_KEY: "{{ valt_glitchip_secret_key }}"
      PORT: 8000
      EMAIL_URL: "smtp://{{ glitchtip_mail.user }}:{{ glitchtip_mail.secret }}@{{ glitchtip_mail.host }}:{{ glitchtip_mail.port }}"
      GLITCHTIP_DOMAIN: "https://{{ glitchtip_host }}"
      DEFAULT_FROM_EMAIL: "{{ glitchtip_mail.user }}"
      CELERY_WORKER_AUTOSCALE: "1,3"
      CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"
      ENABLE_USER_REGISTRATION: "True"
      EMAIL_USE_TLS: "True"
  tasks:
    - name: Start glitchtip containers
      community.docker.docker_compose_v2:
        state: present
        project_name: glitchtip
        definition:
          volumes:
            pg-data:
            uploads:
          services:
            postgres:
              image: postgres:16
              environment:
                POSTGRES_HOST_AUTH_METHOD: "trust"  # Consider removing this and setting a password
              restart: unless-stopped
              volumes:
                - pg-data:/var/lib/postgresql/data
            redis:
              image: redis
              restart: unless-stopped
            web:
              image: glitchtip/glitchtip
              depends_on:
                - postgres
                - redis
              ports:
                - "8000:8000"
              environment: "{{ glitchtip_env  }}"
              restart: unless-stopped
              volumes:
                - uploads:/code/uploads
            worker:
              image: glitchtip/glitchtip
              command: ./bin/run-celery-with-beat.sh
              depends_on:
                - postgres
                - redis
              environment: "{{ glitchtip_env  }}"
              restart: unless-stopped
              volumes:
                - uploads:/code/uploads
            migrate:
              image: glitchtip/glitchtip
              depends_on:
                - postgres
                - redis
              command: "./manage.py migrate"
              environment: "{{ glitchtip_env  }}"
