#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run kafka on target nodes. Run it like usual
# executable script:
#
# > ./run-kafka.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Run kafka on target servers
  hosts: kafka_hosts
  become: yes
  remote_user: root

  roles:
    - { role: kafka, tags: ['kafka'] }
