#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to deploy cryptoprocessing project. Run it like usual executable script:
#
# > ./run-cryptoprocessing.yml
#
---
- name: Configure target servers
  hosts: cryptoprocessing_nodes

  roles:
    - { role: oomag.rails_cryptoprocessing, tags: ['rails'] }
