#!/usr/bin/env ansible-playbook
#
# Playbook to install and run apprise service on target nodes. Apprise is a
# small tool which allows one to send messages about something to various
# services. In my case it usually used to send notifications from backup
# services to Telegram in case of failed tasks.
# Run it like usual executable script:
#
# > ./run-apprise.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure apprise
  hosts: apprise
  remote_user: root

  roles:
    - { role: sorrowless.apprise, tags: ['backup', 'apprise'] }
