#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install glitchtip
  hosts: glitchtip_servers
  become: yes
  become_user: root
  vars:
    glitchtip_env:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      VALKEY_URL: redis://valkey:6379
      SECRET_KEY: "{{ valt_glitchip_secret_key }}"
      PORT: 8000
      EMAIL_URL: "smtp://{{ glitchtip_mail.user }}:{{ glitchtip_mail.secret }}@{{ glitchtip_mail.host }}:{{ glitchtip_mail.port }}"
      GLITCHTIP_DOMAIN: "https://{{ glitchtip_host }}"
      DEFAULT_FROM_EMAIL: "{{ glitchtip_mail.user }}"
      CELERY_WORKER_AUTOSCALE: "1,3"
      CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"
      ENABLE_USER_REGISTRATION: "False"
      ENABLE_SOCIAL_APPS_USER_REGISTRATION: "True"
      EMAIL_USE_TLS: "True"
  tasks:
    - name: Start glitchtip containers
      community.docker.docker_compose_v2:
        state: present
        project_name: glitchtip_6
        definition:
          volumes:
            pg-data:
            uploads:
          services:
            postgres:
              image: postgres:18
              container_name: glitchtip-postgres
              environment:
                POSTGRES_HOST_AUTH_METHOD: "trust"  # Consider removing this and setting a password
              restart: unless-stopped
              volumes:
                - pg-data:/var/lib/postgresql
            valkey:
              image: valkey/valkey:9
              container_name: glitchtip-valkey
              restart: unless-stopped
            web:
              image: glitchtip/glitchtip:6
              container_name: glitchtip-web
              depends_on:
                - postgres
                - valkey
              ports:
                - "127.0.0.1:8080:8000"
              environment: "{{ glitchtip_env }}"
              restart: unless-stopped
              volumes:
                - uploads:/code/uploads
            worker:
              image: glitchtip/glitchtip:6
              container_name: glitchtip-worker
              command: ./bin/run-worker.sh
              depends_on:
                - postgres
                - valkey
              environment: "{{ glitchtip_env }}"
              restart: unless-stopped
              volumes:
                - uploads:/code/uploads
            # migrate need only if update to new version
            # migrate:
            #   image: glitchtip/glitchtip:6
            #   container_name: glitchtip-migrate
            #   depends_on:
            #     - postgres
            #     - valkey
            #   command: ./bin/run-migrate.sh
            #   environment: "{{ glitchtip_env }}"
