#!/usr/bin/env -S ansible-playbook --limit mx -e @vars/extra.yaml
#
# This is a playbook to install full-fledged mail server solution based on
# Postfix and Dovecot. Installation itself includes:
# - TLS role to ensure https connection to Uchiwa dashboard
# - MySQL to store virtual mailboxes
# - Postfix
# - Dovecot
# - Rainloop web-interface
#
# Run it like usual executable script:
#
# > ./run-mail.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Install postfix MTA
  hosts: postfix
  remote_user: root
  roles:
    - { role: sorrowless.postfix, tags: ['postfix'] }
