#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
# Postgresql playbook. Able to install postgresql server, ensure needed
# databases, create users and so on
#
# Parameters to pass documented in defaults yml. Also you can look for
# host_vars/.example directory to see bigger example.
#
# Usage examples:
#
# To install Postgresql server:
# ansible-playbook -i <inventory_file> -b run-postgresql.yml
#
# Also this playbook can be ran like any executable:
#
# > ./run-postgresql.yml
---
- name: Install Postgresql server
  hosts: postgresql_servers
  remote_user: root
  become: yes
  roles:
    - postgresql
