---
- name: Configure target servers
  hosts: arbidex
  remote_user: root

  tasks:
    - name: Add mariaDB repo key
      apt_key:
        keyserver: "hkp://keyserver.ubuntu.com:80"
        id: F1656F24C74CD1D8
        state: present
      tags:
        - mariadb

    - name: Add mariaDB repo
      apt_repository:
        repo: "deb [arch=amd64,arm64,i386,ppc64el] http://mirror.timeweb.ru/mariadb/repo/10.3/ubuntu xenial main"
        state: present
      tags:
        - mariadb

    - name: Install mariaDB 10.3
      package:
        name: mariadb-server
        state: present
      tags:
        - mariadb

    - name: Install python-mysqldb
      package:
        name: python-mysqldb
        state: present
      tags:
        - mariadb

    - name: Ensure DB
      mysql_db:
        name: arbidex
        state: present
        login_user: root
        login_password: 3cmKm81FMY8QEz8s ## пароль в явном виде!!!

    - name: Ensure DB user
      mysql_user:
        login_user: root
        login_password: 3cmKm81FMY8QEz8s
        name: arbidex
        password: h442M1kCjBe9QgDU
        priv: 'arbidex.*:ALL'

    - name: Refclient | Get nodejs 10.x
      shell: 'curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -'
      tags:
        - npm

    - name: Refclient | Install nodejs 10.x
      package:
        name: nodejs
        state: latest
      tags:
        - npm

