#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure VMSelect
  hosts: monitoring_servers
  become: yes
  roles:
    - { role: sorrowless.vminsert, tags: ["server", "vm", "vmselect"] }
