#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure VMAgent
  hosts: monitoring_servers
  become: yes
  roles:
    - { role: sorrowless.vmagent, tags: ["server", "vm", "vmagent"] }
