#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run Bitwarden with nginx and TLS certificates on
# target nodes. Run it like usual executable script:
#
# > ./run-bitwarden.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: bitwarden_servers
  become: yes
  become_user: root

  tasks:
    - name: Ensure bitwarden directories
      file:
        state: directory
        path: "{{ item }}"
        mode: 0750
        owner: root
        group: root
      with_items:
        - /var/bitwarden
      tags:
        - docker
        - bitwarden

    - name: Ensure bitwarden docker container
      community.docker.docker_compose:
        state: present
        project_name: bitwarden
        definition:
          version: '2'
          services:
            bitwarden:
              image: "vaultwarden/server:latest"
              container_name: bitwarden
              ports:
                # host:port
                - "127.0.0.1:8080:80"
              volumes:
                - "/var/bitwarden/:/data"
              environment:
                - YUBICO_CLIENT_ID={{ yubico_client_id }}
                - YUBICO_SECRET_KEY={{ yubico_secret_key }}
                # disable this for the first time
                - SIGNUPS_ALLOWED={{ signups_allowed }}
                - SMTP_HOST={{ smtp_host }}
                - SMTP_FROM={{ smtp_from }}
                - SMTP_PORT={{ smtp_port }}
                - SMTP_SECURITY={{ smtp_security }}
                - SMTP_USERNAME={{ smtp_username }}
                - SMTP_PASSWORD={{ smtp_password }}
                - DOMAIN={{ domain }}
              hostname: bitwarden
              restart: always
              labels:
                - bitwarden
          networks:
            default:
              external:
                name: bw_network
      tags:
        - docker
        - bitwarden

