#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to deploy rails projects. Run it like usual executable script:
#
# > ./run-rails.yml
#
---
- name: Configure target servers
  hosts: rails_projects
  serial: 50
  remote_user: root

  roles:
    - { role: rails, tags: ['rails'] }
