#!/usr/bin/env ansible-playbook
#
# Playbook to install and run mariadb.
# Run it like usual executable script:
#
# > ./run-mariadb.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: mariadb_servers
  become: yes
  become_user: root

  roles:
    - { role: mariadb, tags: ['mysql','mariadb'] }
