#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install blackbox exporters
  hosts: prometheus_blackbox_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_blackbox_exporter, tags: ["blackbox_exporter"] }

- name: Install domain exporters
  hosts: prometheus_domain_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_domain_exporter, tags: ["domain_exporter"] }

- name: Install grok exporters
  hosts: prometheus_grok_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_grok_exporter, tags: ["grok_exporter"] }

- name: Install mysqld exporters
  hosts: prometheus_mysqld_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_mysqld_exporter, tags: ["mysqld_exporter"] }

- name: Install node exporters
  hosts: prometheus_node_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_node_exporter, tags: ["node_exporter"] }

- name: Install postgres exporters
  hosts: prometheus_postgres_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_postgres_exporter, tags: ["postgres_exporter"] }

- name: Install scripts exporters
  hosts: prometheus_scripts_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_scripts_exporter, tags: ["scripts_exporter"] }

- name: Install statsd exporters
  hosts: prometheus_statsd_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_statsd_exporter, tags: ["statsd_exporter"] }

- name: Install HAProxy to ensure reverse proxy to exporters
  hosts: prometheus_clients
  become: yes
  roles:
    - { role: sorrowless.tls, tags: ['tls', 'nginx'] }
    - { role: sorrowless.haproxy, tags: ["haproxy"] }

- name: Install and configure prometheus hosts
  hosts: prometheus_servers
  become: yes
  pre_tasks:
    - name: Preinstall nginx
      package:
        name: nginx
        state: latest
      tags: nginx
  roles:
    - { role: sorrowless.docker, tags: ["docker", "server"] }
    - { role: sorrowless.victoriametrics, tags: ["victoriametrics", "server"] }
    - { role: sorrowless.prometheus_server, tags: ["prometheus_server", "server"] }
    - { role: sorrowless.prometheus_alertmanager, tags: ["prometheus_alertmanager", "alertmanager", "server"] }
    - { role: sorrowless.grafana, tags: ["grafana"] }
    - { role: sorrowless.tls, tags: ['tls', 'nginx'] }
    - { role: sorrowless.nginx, tags: ['nginx'] }
