#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure VMAlert
  hosts: monitoring_servers
  become: yes
  roles:
    - { role: sorrowless.vmalert, tags: ["server", "vm", "vmalert"] }
