#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure AlertManager
  hosts: monitoring_servers
  become: yes
  roles:
    - { role: sorrowless.prometheus_alertmanager, tags: ["server", "vm", "alerts"] }
