---
# You can run separate tags on localhost by something like this:
# ansible-playbook -i 'localhost,' -c local -b -K run-desktop.yml --ask-vault-pass --tags "dotcommon"
- name: Install needed desktop things everywhere
  hosts: all
  remote_user: root
  vars_files:
   - vars/dotfiles_vars.yml

  pre_tasks:
    - name: Create user {{ username }} if does not exists
      user:
        group: "{{ username }}"
        name: "{{ username }}"

  roles:
    - desktop_common
