#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure VMStorage
  hosts: monitoring_servers
  become: yes
  roles:
    - { role: sorrowless.vmstorage, tags: ["server", "vm", "vmstorage"] }
