#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Setup Postgres Exporter
  hosts: prometheus_postgres_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_postgres_exporter, tags: ["exporters", "postgres_exporter"] }
