#!/usr/bin/env ansible-playbook
#
# Playbook to install and run nginx with TLS certificates on target nodes. Run
# it like usual executable script:
#
# > ./run-nginx.yml
#
# For configuration vars look at role variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: nginx
  remote_user: root

  pre_tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: latest

  roles:
    - { role: tls, tags: ['tls'] }
    - { role: nginx, tags: ['nginx'] }
