#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Setup Domain Exporter
  hosts: prometheus_domain_exporters
  become: yes
  roles:
    - { role: sorrowless.prometheus_domain_exporter, tags: ["exporters", "domain_exporter"] }
