#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run minimum viable example of server on target
# nodes. Run it like usual executable script:
#
# > ./run-minimal.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
#
# In case there is no python symlink in Ubuntu Xenial, you can run this
# playbook by:
#
# ansible-playbook -b run-minimal.yml -e 'ansible_python_interpreter=python3' \
#   -i <inventory_file>
---
- name: Configure target servers
  hosts: all
  remote_user: root

  roles:
    - { role: pw_policy, tags: ['security'] }
    - { role: server_common, tags: ['common'] }
    - { role: iptables, tags: ['iptables'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: sudoers, tags: ['sudoers'] }

