---
metainfo:
  placement: DEU, hosters
  company: AKH
ansible_ip: 91.219.23.161
ansible_domainname: deu09.vminsert.openworld.bot
ansible_host: "{{ ansible_ip }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
