---
sc_monitor_openworld_bot:
  - data:
      - job_name: 'deu09-node-exporter'
        scheme: https
        static_configs:
          - labels:
              dns_hostname: 'deu09.vminsert.openworld.bot'
              domainname: 'deu09.vminsert.openworld.bot'
              env: production
              ipaddress: '91.219.23.161'
              project: akh
              scrape_type: node_exporter
              server_type: monitor
            targets:
              - 'deu09.vminsert.openworld.bot:9100'
    filename: 'deu09.vminsert.openworld.bot-node-exporter.yml'
