#!/usr/bin/env ansible-playbook
---
- name: Setup Nginx Exporter
  hosts: nginx_exporters
  become: yes
  roles:
    - { role: andrewgodgivens.prometheus_nginx_exporter, tags: ["exporters", "nginx_exporter"] }
