---
ansible_become: true
ansible_domainname: 62.76.115.218
ansible_host: '{{ ansible_domainname }}'
ansible_ip: 62.76.115.218
ansible_port: '{{ sshd_port }}'
ansible_user: root
metainfo:
  company: AKH
  placement: AKH
