---
metainfo:
  placement: DEU, hosters
  company: AKH
ansible_ip: 93.152.217.218
ansible_domainname: deu08.vminsert.openworld.bot
ansible_host: "{{ ansible_ip }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
