---
metainfo:
  placement: GBR, hosters
  company: AKH
ansible_ip: 194.150.166.100
ansible_domainname: eng02.vminsert.openworld.bot
ansible_host: "{{ ansible_ip }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
