---
vmagent_docker_network_name: prom_network
vmagent_container_name: vmagent
vmagent_docker_image: "victoriametrics/vmagent:v1.113.0"
vmagent_ports: []

vmagent_config_dir: /var/lib/vmagent
vmagent_extra_hosts:
  - "{{ ansible_domainname }}:{{ ansible_ip }}"

vmagent_additional_configs: []
list_of_filenames_to_add: []

vmagent_remotewrite_address: "http://victoriametrics_vminsert:8480"
vmagent_log_level: ERROR
vmagent_command:
  - '-promscrape.config=/etc/prometheus/prometheus.yml'
  - '-remoteWrite.url={{ vmagent_remotewrite_address }}/insert/0/prometheus/'
  - '-loggerLevel={{ vmagent_log_level }}'

prometheus_config:
  global:
    scrape_interval: 30s
  scrape_configs:
    - job_name: "deu10-node-exporter"
      scheme: http
      static_configs:
        - labels:
            dns_hostname: "deu10.vminsert.openworld.bot"
            domainname: "deu10.vminsert.openworld.bot"
            env: production
            instance: "194.87.71.246:9100"
            ipaddress: "194.87.71.246"
            project: akh
            scrape_type: node_exporter
            server_type: monitor
          targets:
            - "victoriametrics_node_exporter:9100"

    - job_name: "vminsert"
      static_configs:
        - targets: ["vminsert:8480"]
          labels:
            project: akh
            env: production
            domainname: "{{ ansible_domainname }}"

    - job_name: "vmselect"
      static_configs:
        - targets: ["vmselect:8481"]
          labels:
            project: akh
            env: production
            domainname: "{{ ansible_domainname }}"

    - job_name: "vmstorage"
      static_configs:
        - targets: ["vmstorage:8482"]
          labels:
            project: akh
            env: production
            domainname: "{{ ansible_domainname }}"

    - job_name: "vmagent"
      static_configs:
        - targets: ["vmagent:8429"]
          labels:
            project: akh
            env: production
            domainname: "{{ ansible_domainname }}"

    - job_name: "vmalert"
      static_configs:
        - targets: ["vmalert:8880"]
          labels:
            project: akh
            env: production
            domainname: "{{ ansible_domainname }}"

vmagent_relabel_configs:
  - source_labels: [__name__]
    regex: 'xray:.*'
    action: keep
  - source_labels: [__name__]
    regex: 'xray_access.*'
    action: drop

vmagent_stack_name: victoriametrics
vmagent_swarm_cluster: true
vm_swarm_manager: "{{ ansible_domainname }}"
vmagent_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []
