#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-sudoers.yml
#
---
- name: Configure sudoers
  hosts: sudoers

  roles:
    - { role: sorrowless.sudoers, tags: ['sudoers'] }