#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Run it like usual executable script:
#
# > ./run-sshd.yml
#
---
- name: Configure sshd
  hosts: all

  roles:
    - { role: sorrowless.sshd, tags: ['sshd'] }
