---
metainfo:
  placement: NLD, the hosting
  company: AKH
ansible_ip: 85.209.153.139
ansible_domainname: nld01.vminsert.openworld.bot
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
