#!/usr/bin/env ansible-playbook
#
# Run it like usual executable script:
#
# > ./run-graphite.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Install and configure Graphite
  hosts: graphite
  remote_user: root
  roles:
    - sorrowless.graphite 
