#!/usr/bin/env ansible-playbook
#
# Run it like usual executable script:
#
# > ./run-grafana.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Install and configure Grafana
  hosts: grafana
  remote_user: root
  roles:
    - sorrowless.grafana
