#!/usr/bin/env ansible-playbook
#
# Run it like usual executable script:
#
# > ./run-tempo.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Install and configure tempo
  hosts: tempo
  remote_user: root
  become: yes
  roles:
    - sorrowless.tempo
