#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Install and configure VMInsert
  hosts: vminsert
  become: yes
  roles:
    - { role: sorrowless.vminsert, tags: ["server", "vm", "vminsert"] }
