---
node_exporter_version: '1.4.0'
node_exporter_run_in_docker: false

node_exporter_host_address: 0.0.0.0
node_exporter_stack_name: victoriametrics
node_exporter_swarm_cluster: true
node_exporter_swarm_manager: monitor.openworld.bot
node_exporter_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []
