---
sc_monitor_openworld.bot:
  - data:
    - job_name: '{{ ansible_domainname }}-node-exporter'
      scheme: https
      static_configs:
        - labels:
            dns_hostname: '{{ ansible_domainname }}'
            domainname: '{{ ansible_domainname }}'
            env: production
            ipaddress: '{{ ansible_ip }}'
            project: akh
            scrape_type: node_exporter
          targets:
            - '{{ ansible_domainname }}:9100'
    filename: '{{ ansible_domainname }}-node-exporter.yml'
