---
vmalert_container_name: vmalert
vmalert_docker_image: "victoriametrics/vmalert:v1.113.0"
vmalert_docker_network_name: prom_network
vmalert_config_dir: /var/lib/vmalert
vmalert_ports: []
vmalert_command:
# vmselect or balancer
- '--datasource.url=http://{{ vmselect_container_name }}:8481/select/0/prometheus'
- '--remoteRead.url=http://{{ vmselect_container_name }}:8481/select/0/prometheus'
# vminsert or balancer
- '--remoteWrite.url=http://{{ vminsert_container_name }}:8480/insert/0/prometheus'
# alertmanager
- '--notifier.url=http://{{ alertmanager_container_name }}:9093/'
# - '--notifier.url=https://{{ vmalertmanager_neighbor_node_01 }}:9093/'  # High Availability
- '--rule=/etc/alerts/*.yml'
# display source of alerts in grafana
- '-external.url=http://{{ alertmanager_container_name }}:3000'   # grafana outside container

vmalert_stack_name: victoriametrics
vmalert_swarm_cluster: true
vm_swarm_manager: monitor.openworld.bot
vmalert_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []

vmalert_additional_alerts:
- filename: host_status.yml
  data:
    groups:
    - name: HostStatus.rules
      rules:
      - alert: HostIsDown
        expr: 'sum by (dns_hostname,env,domainname) (up{scrape_type!="custom",scrape_type!="blackbox_exporter",hypervisor_type="virtual_machine"}) == 0'
        for: 30s
        labels:
          severity: critical
          hypervisor_type: virtual_machine
        annotations:
          description: !unsafe "Victoriametrics jobs don`t have live targets anymore."
          summary: !unsafe "Host {{ $labels.dns_hostname }} is down"
          summary_resolved: !unsafe "Host {{ $labels.dns_hostname }} is up"
      - alert: CloudHostIsDown
        expr: 'sum by (dns_hostname,env,domainname) (up{scrape_type!="custom",scrape_type!="blackbox_exporter",hypervisor_type="cloud_virtual_machine"}) == 0'
        for: 30s
        labels:
          severity: critical
          hypervisor_type: cloud_virtual_machine
        annotations:
          description: !unsafe "Victoriametrics jobs don`t have live targets anymore."
          summary: !unsafe "Host {{ $labels.dns_hostname }} is down"
          summary_resolved: !unsafe "Host {{ $labels.dns_hostname }} is up"
      - alert: HypervisorIsDown
        expr: 'sum by (dns_hostname,env,domainname) (up{scrape_type!="custom",scrape_type!="blackbox_exporter",hypervisor_type="hypervisor"}) == 0'
        for: 30s
        labels:
          severity: critical
          hypervisor_type: hypervisor
        annotations:
          description: !unsafe "Victoriametrics jobs don`t have live targets anymore."
          summary: !unsafe "Hypervisor {{ $labels.dns_hostname }} is down"
          summary_resolved: !unsafe "Hypervisor {{ $labels.dns_hostname }} is up"

- filename: smartctl_alerts.yml
  data:
    groups:
    - name: smartctl.rules
      rules:
      - alert: DiskHealth
        expr: "smartprom_health_status != 0"
        for: 30m
        labels:
          severity: critical
        annotations:
          summary: !unsafe "Disk is bad in {{ $labels.dns_hostname }}."
          description: !unsafe "smartprom health status test is not PASSED."
      - alert: DiskTemperature
        expr: "smartprom_drive_temperature_raw > 50 or smartprom_temperature_celsius_raw > 50 or smartprom_temperature_current > 50"
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Disk temperature is high in{{ $labels.dns_hostname }}."
          description: !unsafe "Disk temperature is high in {{ $labels.dns_hostname }}."
      - alert: DiskBadSectors
        expr: "smartprom_reallocated_sector_ct != 100 or smartprom_reallocated_sector_ct_raw > 1 or smartprom_scsi_grown_defect_list > 1 or smartprom_scsi_pending_defects_count > 1 or smartprom_available_reservd_space < 99 or smartprom_pending_sector_count_raw > 1"
        for: 180m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "The bad sector count is increasing in {{ $labels.dns_hostname }}."
          description: !unsafe "The bad sector count is increasing in {{ $labels.dns_hostname }}."
      - alert: DiskErrors
        expr: "smartprom_crc_error_count_raw > 100 or smartprom_uncorrectable_error_cnt_raw > 1"
        for: 180m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "The error count is increasing in {{ $labels.dns_hostname }}."
          description: !unsafe "The error count is increasing in {{ $labels.dns_hostname }}."
      - alert: DiskUnsafeShutdown
        expr: "increase(smartprom_unsafe_shutdown_count_raw[3h]) > 3"
        for: 180m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "The unsafe shutdown count is unusual high in {{ $labels.dns_hostname }}."
          description: !unsafe "The unsafe shutdown count is unusual high in {{ $labels.dns_hostname }}."
      - alert: DiskWearout
        expr: "smartprom_workld_media_wear_indic_raw / 1024 > 50 or smartprom_media_wearout_indicator_value < 50"
        for: 360m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Disk wearout is high in {{ $labels.dns_hostname }}."
          description: !unsafe "Disk wearout is high in {{ $labels.dns_hostname }}."
- filename: alertmanager_notify_status.yml
  data:
    groups:
    - name: alertmanager_notify_status.rules
      rules:
      - alert: AlertmanagerNotifyFailed
        expr: ceil(rate(failed_notify{}[5m]/300)) > 0
        for: 60s
        labels:
          severity: critical
          is_alert_bot_status: "True"
        annotations:
          summary: !unsafe "{{ $labels.dns_hostname }} alertmanager failed to send alerts."
          summary_resolved: !unsafe "{{ $labels.dns_hostname }} alertmanager send alerts success."
- filename: bitwarden_alerts.yml
  data:
    groups:
    - name: bitwarden.rules
      rules:
      - alert: BitwardenError
        expr: ceil(rate(bitwarden_error{}[5m]/300)) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "{{ $labels.dns_hostname }} bitwarden container has errors."
          summary_resolved: !unsafe "{{ $labels.dns_hostname }} NO errors in container bitwarden."
          description: !unsafe "{{ $labels.dns_hostname }} bitwarden container has errors."
- filename: nginx_server_internal_error_alerts.yml
  data:
    groups:
    - name: nginx_server_internal_error_alerts
      rules:
      - alert: ServerInternalError
        expr: rate(http_response_time_seconds_hist_count{status=~"5.+",dns_hostname!="etlgr_site_proxy"}[5m]/300) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "{{ $labels.dns_hostname }} Nginx handle 500 response code."
          summary_resolved: !unsafe "{{ $labels.dns_hostname }} There no 500 response codes."
          description: !unsafe "{{ $labels.dns_hostname }} Server Internal Error as response on http request."
- filename: gitlab_backup_errors.yml
  data:
    groups:
    - name: bitwarden.rules
      rules:
      - alert: GitlabBackupError
        expr: ceil(rate(gitlab_backup_errors{}[5m]/300)) > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: !unsafe "{{ $labels.dns_hostname }} gitlab backup has errors."
          summary_resolved: !unsafe "{{ $labels.dns_hostname }} There's no errors last 5 minutes."
          description: !unsafe "{{ $labels.dns_hostname }} gitlab backup has errors."
- filename: node_exporter_disk.yml
  data:
    groups:
    - name: disk.rules
      rules:
      - alert: UnusualDiskReadRate
        expr: sum by (instance,dns_hostname,hypervisor_type,domainname) (irate(node_disk_read_bytes_total{hypervisor_type!="hypervisor"}[2m])) / 1024 / 1024 > 50
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk read rate (more than 50mbit/s) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk read rate is under 50mbit/s on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is probably reading too much data (> 50 MB/s) on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: UnusualDiskWriteRate
        expr: sum by (instance,dns_hostname,hypervisor_type,domainname) (irate(node_disk_read_bytes_total{hypervisor_type!="hypervisor"}[2m])) / 1024 / 1024 > 50
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk write rate (more than 50mbit/s) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk write rate is under 50mbit/s on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is probably writing too much data (> 50 MB/s)on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: UnusualHypervisorDiskReadRate
        expr: sum by (instance,dns_hostname,hypervisor_type,domainname) (irate(node_disk_read_bytes_total{hypervisor_type="hypervisor"}[2m])) / 1024 / 1024 > 300
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk read rate (more than 300mbit/s) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk read rate is under 300mbit/s on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is probably reading too much data (> 300 MB/s) on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: UnusualHypervisorDiskWriteRate
        expr: sum by (instance,dns_hostname,hypervisor_type,domainname) (irate(node_disk_read_bytes_total{hypervisor_type="hypervisor"}[2m])) / 1024 / 1024 > 300
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk write rate (more than 300mbit/s) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk write rate is under 300mbit/s on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is probably writing too much data (> 300 MB/s)on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: OutOfDiskSpace
        expr: node_filesystem_avail_bytes{project != "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} / node_filesystem_size_bytes{project != "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} * 100 < 10 AND node_filesystem_avail_bytes{project != "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} / 1024 / 1024 / 1024 < 15
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Out of disk space on {{ $labels.dns_hostname }}, only {{ printf \"%.2f\" $value }}Gb available on {{ $labels.mountpoint }} mountpoint"
          summary_resolved: !unsafe "Disk usage has enough free space on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is almost full {{ $labels.dns_hostname }}"
      - alert: OutOfDiskSpaceEtlgr
        expr: node_filesystem_avail_bytes{project = "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} / node_filesystem_size_bytes{project = "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} * 100 < 20 AND node_filesystem_avail_bytes{project = "etlgr", device!~"tmpfs|lxcfs|cgmfs", mountpoint!~".*swap.*"} / 1024 / 1024 / 1024 < 25
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Out of disk space on {{ $labels.dns_hostname }}, only {{ printf \"%.2f\" $value }}Gb available on {{ $labels.mountpoint }} mountpoint"
          summary_resolved: !unsafe "Disk usage has enough free space on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is almost full {{ $labels.dns_hostname }}"
      - alert: OutOfDiskSpaceEtlgrmailsData
        expr: node_filesystem_avail_bytes{dns_hostname="etlgr_mail_app", mountpoint="/mount/etlgrmails/data"} / node_filesystem_size_bytes{dns_hostname="etlgr_mail_app", mountpoint="/mount/etlgrmails/data"} * 100 < 20 AND node_filesystem_avail_bytes{dns_hostname="etlgr_mail_app", mountpoint="/mount/etlgrmails/data"} / 1024 / 1024 / 1024 < 200
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Out of disk space on {{ $labels.dns_hostname }}, only {{ printf \"%.2f\" $value }}Gb available on {{ $labels.mountpoint }} mountpoint"
          summary_resolved: !unsafe "Disk usage has enough free space on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is almost full {{ $labels.dns_hostname }}"
      - alert: OutOfDiskSpaceClickhouseVar
        expr: node_filesystem_avail_bytes{dns_hostname="clickhouse-hq-vsrv01.auto.local", mountpoint="/var"} / 1024 / 1024 / 1024 < 62
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Out of disk space on {{ $labels.dns_hostname }}, only {{ printf \"%.2f\" $value }}Gb available on {{ $labels.mountpoint }} mountpoint"
          summary_resolved: !unsafe "Disk usage has enough free space on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is almost full {{ $labels.dns_hostname }}"
      - alert: OutOfInodes
        expr: node_filesystem_files_free{mountpoint ="/rootfs"} / node_filesystem_files{mountpoint ="/rootfs"} * 100 < 5
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Out of inodes on {{ $labels.dns_hostname }}, only {{ printf \"%.2f\" $value }} left"
          summary_resolved: !unsafe "Inodes count is under 95% on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk is almost running out of available inodes on {{ $labels.dns_hostname }}"
      - alert: UnusualDiskReadLatency
        expr: rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 100
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk read latency (read operations > 100ms) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk read latency is okay on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk latency is growing (read operations > 100ms) on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      - alert: UnusualDiskWriteLatency
        expr: rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 100
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: !unsafe "Unusual disk write latency (write operations > 100ms) on {{ $labels.dns_hostname }}"
          summary_resolved: !unsafe "Disk write latency is okay on {{ $labels.dns_hostname }}"
          description: !unsafe "Disk latency is growing (write operations > 100ms) on {{ $labels.dns_hostname }}\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
- filename: victoriametrics.yml
  data:
    groups:
    - name: vmagent.rules
      rules:
      - alert: ScrapeTargetIsDown
        expr: 'sum by (dns_hostname,env,domainname) (vm_promscrape_targets{status="down"}) > 0'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: !unsafe "Scrape targets in the amount {{ $value }} on host {{ $labels.dns_hostname }} are down."
          summary_resolved: !unsafe "{{ $labels.dns_hostname }} scrape targets are up."
          description: !unsafe "Scrape targets in the amount {{ $value }} on host {{ $labels.dns_hostname }} are down."
      - alert: ScrapeTargetIsUnavailable
        expr: 'group by (dns_hostname,env,domainname,project,job) (up{} offset 24h unless on (instance) up{}) == 1'
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: !unsafe "Scrape target with job {{ $labels.job }} on host {{ $labels.dns_hostname }} is unavailable."
          summary_resolved: !unsafe "{{ $labels.job }} scrape target is available."
          description: !unsafe "Scrape target with job {{ $labels.job }} on host {{ $labels.dns_hostname }} is unavailable."
