---
vmselect_container_name: vmselect
vmselect_docker_image: "victoriametrics/vmselect:v1.113.0-cluster"
vmselect_docker_network_name: prom_network
vmselect_command:
- '-storageNode={{ vmstorage_container_name }}:8401'
- '-storageNode=rus01.vmstorage.openworld.bot:8401'
- '-storageNode=nld01.vmstorage.openworld.bot:8401'
- '-storageNode=usa01.vmstorage.openworld.bot:8401'
- '-storageNode=usa02.vmstorage.openworld.bot:8401'
- '-storageNode=eng01.vmstorage.openworld.bot:8401'
- '-storageNode=deu01.vmstorage.openworld.bot:8401'
- '-storageNode=deu02.vmstorage.openworld.bot:8401'
- '-storageNode=deu03.vmstorage.openworld.bot:8401'
- '-storageNode=deu04.vmstorage.openworld.bot:8401'
- '-storageNode=deu05.vmstorage.openworld.bot:8401'
- '-storageNode=deu06.vmstorage.openworld.bot:8401'
- '-storageNode=deu07.vmstorage.openworld.bot:8401'
- '-search.maxSamplesPerSeries=9000000'
- '-search.maxSeries=40000000'
# High Availability
# - '--storageNode={{ vmstorage_neighbor_node_01 }}:8401'
# - '--replicationFactor=2'
# - '-dedup.minScrapeInterval=1ms'

vmselect_stack_name: victoriametrics
vmselect_swarm_cluster: true
vm_swarm_manager: monitor.openworld.bot
vmselect_swarm_deploy:
  mode: replicated
  replicas: 1
  placement:
    constraints: []
