---
traefik_environment_vars:
  - CF_DNS_API_TOKEN=IxhtY0R_SaUslq4fGrZ3oOtBFUOK2DMV3U_gAj9Z

traefik_docker_tag: v3.6.6
traefik_docker_network_name: 'prom_network'
traefik_docker_networks:
  prom_network:
    name: "prom_network"
    external: true
traefik_swarm_cluster: true
# traefik_swarm_manager value is inventory/hosts name, not actual DNS one
traefik_swarm_manager: "{{ ansible_domainname }}"
traefik_web_host: "{{ ansible_ip }}"

traefik_dynamic_confs:
  global_basicauth.yml: "{{ vault_traefik_global_basicauth }}"

# Publish on host directly
traefik_ports:
  - target: 80
    published: 80
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: tcp
    mode: host
