---
metainfo:
  placement: AKH
  company: AKH
ansible_ip: 62.76.115.219
ansible_domainname: 62.76.115.219
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
