---
metainfo:
  placement: AKH
  company: AKH
ansible_ip: 178.17.57.17
ansible_domainname: 178.17.57.17
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
