---
cluster_name: "patroni"
patroni_name: "node_1"

cluster_host_ip: "{{ ansible_ip }}"
cluster_database_dir: /var/lib/postgres_patroni

consul_docker_command: "agent -server -advertise {{ cluster_host_ip }} -bootstrap-expect 1 -client 0.0.0.0"

postgres_superuser_password: "{{ PG_SUPERUSER_PASSWD }}"
postgres_replication_password: "{{ PG_REPLICATION_PASSWD }}"
patroni_admin_password: "{{ PATRONI_ADMIN_PASSWD }}"

patroni_manage_os_user: false
postgres_user_uid: 108
patroni_docker_uid: 70

postgres_config_dir: "/var/lib/postgresql/postgresql/data"
postgres_data_dir: "/var/lib/postgresql/postgresql/data"
postgres_user_uid: 108
postgres_connect_port: 5433
patroni_expose_ports:
    - "127.0.0.1:8008:8008"
    - "127.0.0.1:5433:5432"

postgresql_pg_hba:
  - host all all 127.0.0.1/32 md5
  - host all all 172.16.0.0/12 md5
  - host all all 10.0.0.0/8 md5
  - host replication {{ postgres_replication_username }} 127.0.0.1/32 md5

dsc_postgres_parametrs:
    max_connections: 550
    archive_mode: "on"
    archive_timeout: "60s"
    archive_command: "wal-g wal-push %p"

patroni_extra_env:
  WALG_CONFIG_FILE: "/.walg.json"

patroni_extra_volumes:
  - "/var/lib/postgres_patroni/.walg.json:/.walg.json:ro"
  - "/usr/local/bin/wal-g:/usr/bin/wal-g:ro"
