---
metainfo:
  placement: DEU, the hosting
  company: AKH
ansible_ip: 92.118.232.70
ansible_domainname: deu01.vminsert.openworld.bot
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
