---
vmagent_docker_network_name: prom_network
vmagent_container_name: vmagent
vmagent_docker_image: "victoriametrics/vmagent:v1.113.0"

vmagent_config_dir: /var/lib/vmagent
vmagent_extra_hosts:
  - "{{ ansible_host }}:{{ ansible_ip }}"

vmagent_swarm_cluster: false

vmagent_remotewrite_address: "https://vminsert.akh.oom.ag"
vmagent_log_level: INFO
vmagent_command:
  - '-promscrape.config=/etc/prometheus/prometheus.yml'
  - '-remoteWrite.url={{ vmagent_remotewrite_address }}/insert/0/prometheus/'
  - '-remoteWrite.basicAuth.username={{ vault_group_vmagent_command.basicauth.username }}'
  - '-remoteWrite.basicAuth.password={{ vault_group_vmagent_command.basicauth.password }}'
  - '-loggerLevel={{ vmagent_log_level }}'

vmagent_additional_configs:
  - "{{ host_scrape_configs }}"
