---
metainfo:
  placement: DEU, webhost
  company: AKH
ansible_ip: 45.128.99.143
ansible_domainname: deu13.vminsert.openworld.bot
ansible_host: "{{ ansible_ip }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
