#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to recreate host ssh-keys. Run it like usual executable
# script:
#
# > ./run-refresh-ssh-host-keys.yml

---
- name: Configure target servers
  hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Collect old ssh keys
    find:
      paths: /etc/ssh
      patterns: ssh_host_*
    register: ssh_keys

  - name: Delete old ssh keys
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ ssh_keys.files }}"

  - name: Generate new ssh host keys
    shell:
      cmd: |
        dpkg-reconfigure openssh-server -f noninteractive

  - name: Restart sshd service
    systemd:
      state: restarted
      name: sshd
