---
host_scrape_configs:
  - data:
    - job_name: '{{ ansible_domainname }}-node-exporter'
      scheme: http
      static_configs:
        - labels:
            dns_hostname: '{{ ansible_domainname }}'
            domainname: '{{ domainname | default(ansible_domainname) }}'
            env: production
            ipaddress: '{{ ansible_ip }}'
            project: akh
            scrape_type: node_exporter
            server_type: '{{ server_type | default("proxy_v2") }}'
            country: '{{ country | default("") }}'
            provider: '{{ provider | default("") }}'
          targets:
            - '{{ node_exporter_host_address }}:9100'
    filename: '{{ ansible_domainname }}-node-exporter.yml'
