---
metainfo:
  placement: DEU, the hosting
  company: AKH
ansible_ip: 171.22.120.168
ansible_domainname: deu06.vminsert.openworld.bot
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
