---
host_scrape_configs:
  - data:
    - job_name: '{{ ansible_domainname }}-node-exporter'
      scheme: http
      static_configs:
        - labels:
            dns_hostname: '{{ ansible_domainname }}'
            domainname: '{{ ansible_domainname }}'
            env: production
            ipaddress: '{{ ansible_ip }}'
            project: akh
            scrape_type: node_exporter
          targets:
            - '{{ node_exporter_host_address }}:9100'
    filename: '{{ ansible_domainname }}-node-exporter.yml'
