---
- name: Switch to mitogen for current deployment project
  hosts: localhost

  tasks:
    - name: Create library directory if it does not exists yet
      file:
        state: directory
        path: ../library
        mode: 0755

    - name: Download mitogen binary
      ansible.builtin.git:
        repo: "https://github.com/mitogen-hq/mitogen.git"
        dest: "../library/mitogen-master"
        version: "v0.3.3"

    - name: Ensure mitogen strategies in ansible config
      lineinfile:
        path: ../ansible.cfg
        line: "strategy_plugins = library/mitogen-master/ansible_mitogen/plugins/strategy"
        insertafter: '\[defaults\]'
      when: set_local_ansible_config is defined

    - name: Ensure mitogen usage in ansible config
      lineinfile:
        path: ../ansible.cfg
        line: 'strategy = mitogen_linear'
        insertafter: '^strategy_plugins = .*'
      when: set_local_ansible_config is defined
