#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run redis server. Run it like usual executable
# script:
#
# > ./run-redis.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Configure target servers
  hosts: redis_servers
  become: yes
  become_user: root

  roles:
    - { role: sorrowless.redis, tags: ['redis'] }
