---
metainfo:
  placement: RU, Ufo hosting
  company: AKH
ansible_ip: 45.144.30.121
ansible_domainname: rus01.vminsert.openworld.bot
ansible_host: "{{ ansible_domainname }}"
ansible_port: "{{ sshd_port }}"
ansible_user: root
ansible_become: true
