#!/usr/bin/env ansible-playbook
#
# Playbook to install and run Jenkins with nginx and TLS certificates on
# target nodes. Run it like usual executable script:
#
# > ./run-jenkins.yml
#
# For configuration vars look at roles variables or host_vars/.example
# directory.
---
- name: Setup OpenJDK
  import_playbook: configuration/run-java.yml
  tags:
    - java

- name: Setup Jenkins
  import_playbook: services/run-jenkins.yml
  tags:
    - jenkins

- name: Ensure TLS certificates
  import_playbook: services/run-tls.yml
  tags:
    - tls
    - nginx

- name: Setup Nginx
  import_playbook: services/run-nginx.yml
  tags:
    - nginx
