#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
# Playbook to install and run backup reporter or collector in cron job
#
# > ./run-backup-reporter.yml
---
- name: Install and configure backup reporter
  hosts: backup_reporters, backup_collectors
  remote_user: root
  tasks:
    - name: Ensure variables
      ansible.builtin.set_fact:
        backup_reporter_config_dir: "{{ backup_reporter_config_dir | default('/etc/backup-reporter') }}"
        backup_reporter_google_spreadsheet_credentials: "{{ backup_reporter_google_spreadsheet_credentials | default('') }}"
        backup_reporter_docker_postgres: "{{ backup_reporter_docker_postgres | default(False) }}"
        backup_reporter_container_name: "{{ backup_reporter_container_name | default('None') }}"
        backup_reporter_files_bucket: "{{ backup_reporter_files_bucket | default(False) }}"
        backup_reporter_files: "{{ backup_reporter_files | default(False) }}"
        backup_reporter_files_mask: "{{ backup_reporter_files_mask | default('*.tar.gz') }}"
        backup_reporter_backups_dir: "{{ backup_reporter_backups_dir | default('/var/backups') }}"
        backup_reporter_collector: "{{ backup_reporter_collector | default(False) }}"
        backup_reporter_sheet_owner: "{{ backup_reporter_sheet_owner | default('None') }}"
        backup_reporter_spreadsheet_name: "{{ backup_reporter_spreadsheet_name | default('None') }}"
        backup_reporter_worksheet_name: "{{ backup_reporter_worksheet_name | default('None') }}"
        backup_reporter_bucket: "{{ backup_reporter_bucket | default('[]') }}"
        backup_reporter_python_executable: "{{ backup_reporter_python_executable | default('python3') }}"
        backup_reporter_customer: "{{ backup_reporter_customer | default('') }}"
        backup_reporter_supposed_backups_count: "{{ backup_reporter_supposed_backups_count | default('') }}"
        backup_reporter_description: "{{ backup_reporter_description | default('') }}"
      tags:
        - always

    - name: Ensure config directory
      ansible.builtin.file:
        path: "{{ backup_reporter_config_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure pip is installed
      ansible.builtin.package:
        name:
          - python3-pip
          - python3-venv
          - python3-virtualenv
        state: present

    - name: Ensure pip3 is latest version and required packages installed
      ansible.builtin.pip:
        executable: pip3
        name: pip
        state: latest

    - name: Ensure virtualenv
      ansible.builtin.shell:
        cmd: "{{ backup_reporter_python_executable }} -m venv backup_reporter"
      args:
        chdir: "/opt"
        creates: "/opt/backup_reporter"

    - name: Ensure backup-reporter python package
      ansible.builtin.pip:
        virtualenv: "/opt/backup_reporter"
        name: backup-reporter
        state: latest

    - name: Set google credentials json
      ansible.builtin.copy:
        dest: "{{ backup_reporter_config_dir }}/google_creds.yml"
        content: "{{ backup_reporter_google_spreadsheet_credentials }}"
        mode: '0700'
      register: backup_reporter_google_spreadsheet_credentials_path
      when: backup_reporter_google_spreadsheet_credentials is defined

    - name: Set config file
      ansible.builtin.copy:
        dest: "{{ backup_reporter_config_dir }}/backup_reporter_config.yml"
        content: |
          docker_postgres: {{ backup_reporter_docker_postgres }}
          container_name: "{{ backup_reporter_container_name }}"
          files_bucket: {{ backup_reporter_files_bucket }}
          files: {{ backup_reporter_files }}
          files_mask: "{{ backup_reporter_files_mask }}"
          backups_dir: "{{ backup_reporter_backups_dir }}"

          collector: {{ backup_reporter_collector }}

          sheet_owner: "{{ backup_reporter_sheet_owner }}"
          google_spreadsheet_credentials_path: "{{ backup_reporter_config_dir }}/google_creds.yml"
          spreadsheet_name: "{{ backup_reporter_spreadsheet_name }}"
          worksheet_name: "{{ backup_reporter_worksheet_name }}"
          customer: "{{ backup_reporter_customer | default('') }}"
          supposed_backups_count: "{{ backup_reporter_supposed_backups_count | default('') }}"
          description: "{{ backup_reporter_description }}"

          bucket:
          {{ backup_reporter_bucket | to_nice_yaml }}
        mode: '0700'

    - name: Set daily cron-job with reporter
      ansible.builtin.cron:
        name: "Backup report"
        minute: "0"
        hour: "1"
        job: "/opt/backup_reporter/bin/backup-reporter --config {{ backup_reporter_config_dir }}/backup_reporter_config.yml"

    - name: Explicitly run report command
      ansible.builtin.shell:
        cmd: "/opt/backup_reporter/bin/backup-reporter --config {{ backup_reporter_config_dir }}/backup_reporter_config.yml"
      tags:
        - never
        - report
