#!/usr/bin/env -S ansible-playbook -e @vars/extra.yaml
#
---
- name: Setup docker 
  import_playbook: services/run-docker.yml

- name: Ensure elasticsearch running on hosts
  import_playbook: services/run-elasticsearch.yml
